from django.urls import path, include
from .views import BookList, BookViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Still keep the simple list view
    path('books/', BookList.as_view(), name='book-list'),

    # Add all CRUD routes generated by the router
    path('', include(router.urls)),
]